"""Finalized-boot phases for the checkpointed Apple Silicon image.

This whole-file module is the finalized-only producer seam. It imports the
configured/shared implementation, but the configured stage never imports this
module, so boot finalization changes cannot invalidate the installed package
closure.
"""

from __future__ import annotations

import os
from pathlib import Path
import re
import shutil
import subprocess
import textwrap

from . import archinstall_adapter as arch
from .command import capture, capture_identifier, require_text
from .configured_phases import (
    PROVISION_KEYFILE,
    PROVISION_STATE_DIR,
    TARGET_DEFERRED_BOOT_HOOKS,
    _blkid_uuid,
    _boot_backend,
    _boot_intent,
    _btrfs_root_device,
    _esp_device,
    _find_label_entries,
    _is_devnull_symlink,
    _limine_efi_names,
    _provision_install_encrypted,
    _read_efibootmgr,
    _run_target_setup_command,
    _storage_intent,
    cleanup_target_hook_masks,
    prepare_install_target,
)
from .context import InstallContext
from .ui import info


def finalize_boot(ctx: InstallContext) -> None:
    from . import asahi_limine

    if asahi_limine.selected(ctx):
        asahi_limine.finalize(ctx)
        return

    if _boot_backend(ctx) == "asahi-grub":
        from .asahi_boot import finalize_asahi_grub_boot

        finalize_asahi_grub_boot(ctx)
    else:
        finalize_limine_boot(ctx)


def finalize_limine_boot(ctx: InstallContext) -> None:
    """Finalize Limine after target system setup has written all dynamic
    boot drop-ins (hibernation, hardware quirks, protected-mode ESP settings).
    """
    if not (ctx.target / "usr" / "bin" / "limine-update").exists():
        raise RuntimeError("/usr/bin/limine-update missing in target")

    default_limine = ctx.target / "etc" / "default" / "limine"
    if not default_limine.exists():
        raise RuntimeError(f"{default_limine} missing")

    default_text = default_limine.read_text()
    if "@@CMDLINE@@" in default_text:
        raise RuntimeError(f"{default_limine} still contains @@CMDLINE@@")

    config_text = _limine_combined_config_text(ctx, default_text)
    cmdline = _limine_kernel_cmdline(config_text)
    if not cmdline.strip():
        raise RuntimeError(f"{default_limine} has no KERNEL_CMDLINE[default]+= line")
    if "root=" not in cmdline:
        raise RuntimeError(f"cmdline parsed from {default_limine} has no root=: {cmdline}")

    esp_path = _limine_setting(config_text, "ESP_PATH", "/boot") or "/boot"
    esp_root = ctx.target / esp_path.lstrip("/")
    if not esp_root.is_dir():
        raise RuntimeError(f"Limine ESP_PATH does not exist in target: {esp_root}")

    snapper_root = ctx.target / "etc" / "snapper" / "configs" / "root"
    if not snapper_root.exists():
        raise RuntimeError(f"{snapper_root} missing")

    limine_conf = esp_root / "limine.conf"
    if not limine_conf.exists():
        raise RuntimeError(f"{limine_conf} missing")

    if _is_arm_machine():
        # limine-entry-tool 1.36 only generates entries for x86_64 and the
        # Arch Linux ARM kernel does not ship the pkgbase file its mkinitcpio
        # hook discovers.  Keep the package-owned tooling for x86, but install
        # a small ARM updater that builds the UKI from /boot/Image and owns one
        # clearly delimited entry in limine.conf.  The pacman hook keeps that
        # entry current on later linux-aarch64 upgrades.
        if "cryptdevice=" in cmdline:
            cmdline = _prepare_arm_systemd_encryption(ctx, cmdline)
        kernel_cmdline = ctx.target / "etc" / "kernel" / "cmdline"
        kernel_cmdline.write_text(cmdline + "\n")
        _install_arm_limine_updater(ctx)
        subprocess.run(
            ["arch-chroot", str(ctx.target), "/usr/local/bin/omarchy-arm-limine-update"],
            check=True,
        )
    else:
        subprocess.run(["arch-chroot", str(ctx.target), "limine-update"], check=True)

    subprocess.run(
        ["arch-chroot", str(ctx.target), "btrfs", "quota", "disable", "/"],
        check=False,
        capture_output=True,
    )
    if "Omarchy" not in limine_conf.read_text():
        raise RuntimeError(f"{limine_conf} has no Omarchy entry")
    encryption_parameter = "rd.luks.name=" if _is_arm_machine() else "cryptdevice="
    if ctx.encrypt and encryption_parameter not in limine_conf.read_text():
        raise RuntimeError(
            f"encrypted install but {limine_conf} has no {encryption_parameter}"
        )


def _is_arm_machine(machine: str | None = None) -> bool:
    return (machine or os.uname().machine).lower() in {"aarch64", "arm64"}


ARM_ENCRYPTION_HOOKS_DROPIN = r'''# Generated by the Omarchy ARM installer.
# Keep Archinstall's systemd initramfs and insert its matching encryption hook
# immediately before filesystems.
_omarchy_arm_hooks=()
_omarchy_arm_encrypt_added=false
_omarchy_arm_plymouth_added=false
for _omarchy_arm_hook in "${HOOKS[@]}"; do
  case $_omarchy_arm_hook in
    encrypt|sd-encrypt)
      ;;
    plymouth)
      if ! $_omarchy_arm_plymouth_added; then
        _omarchy_arm_hooks+=(plymouth)
        _omarchy_arm_plymouth_added=true
      fi
      ;;
    filesystems)
      if ! $_omarchy_arm_plymouth_added; then
        _omarchy_arm_hooks+=(plymouth)
        _omarchy_arm_plymouth_added=true
      fi
      if ! $_omarchy_arm_encrypt_added; then
        _omarchy_arm_hooks+=(sd-encrypt)
        _omarchy_arm_encrypt_added=true
      fi
      _omarchy_arm_hooks+=(filesystems)
      ;;
    *)
      _omarchy_arm_hooks+=("$_omarchy_arm_hook")
      ;;
  esac
done
if ! $_omarchy_arm_plymouth_added; then
  _omarchy_arm_hooks+=(plymouth)
fi
if ! $_omarchy_arm_encrypt_added; then
  _omarchy_arm_hooks+=(sd-encrypt)
fi
HOOKS=("${_omarchy_arm_hooks[@]}")
unset _omarchy_arm_hooks _omarchy_arm_encrypt_added _omarchy_arm_plymouth_added
unset _omarchy_arm_hook
'''


def _prepare_arm_systemd_encryption(ctx: InstallContext, cmdline: str) -> str:
    match = re.search(
        r"(?<!\S)cryptdevice=(?P<device>[^:\s]+):(?P<name>[^:\s]+)(?::[^\s]+)?",
        cmdline,
    )
    if not match:
        raise RuntimeError(f"ARM encrypted command line has no usable cryptdevice=: {cmdline}")

    device_spec = match.group("device")
    mapper_name = match.group("name")
    if device_spec.startswith("UUID="):
        luks_uuid = device_spec.removeprefix("UUID=")
    else:
        device = capture_identifier(
            ["blkid", "-t", device_spec, "-o", "device"],
            f"the encrypted device matching {device_spec}",
        )
        if not device:
            raise RuntimeError(f"could not resolve encrypted device {device_spec}")
        luks_uuid = _blkid_uuid(device)

    dropin = ctx.target / "etc" / "mkinitcpio.conf.d" / "90-omarchy-arm-encryption.conf"
    dropin.parent.mkdir(parents=True, exist_ok=True)
    dropin.write_text(ARM_ENCRYPTION_HOOKS_DROPIN)

    crypttab = ctx.target / "etc" / "crypttab.initramfs"
    crypttab.write_text(f"{mapper_name} UUID={luks_uuid} none luks,discard\n")

    systemd_parameter = f"rd.luks.name={luks_uuid}={mapper_name}"
    cmdline = cmdline[: match.start()] + systemd_parameter + cmdline[match.end() :]
    cmdline = re.sub(
        r"(?<!\S)cryptkey=rootfs:(?P<path>\S+)",
        r"rd.luks.key=\g<path>",
        cmdline,
    )
    if not re.search(r"(?<!\S)splash(?!\S)", cmdline):
        cmdline += " splash"
    # QEMU's ARM virt machine advertises its PL011 UART as firmware stdout.
    # Without an explicit virtual console, Linux makes ttyAMA0 /dev/console
    # and systemd's initramfs password agent becomes the only visible unlock
    # prompt even when virtio-gpu and Plymouth are present. Make the graphical
    # console authoritative for normal installed systems. The acceptance
    # harness drives this display through QMP, so test-only serial wiring never
    # needs to leak into the target command line.
    cmdline = re.sub(r"(?<!\S)console=\S+", "", cmdline)
    cmdline = re.sub(r"\s+", " ", cmdline).strip()
    cmdline += " console=tty0"
    if not re.search(r"(?<!\S)plymouth\.ignore-serial-consoles(?!\S)", cmdline):
        cmdline += " plymouth.ignore-serial-consoles"
    return cmdline


ARM_LIMINE_UPDATE_SCRIPT_TEMPLATE = r'''#!/bin/bash
set -euo pipefail

kernel="@KERNEL_PACKAGE@"
preset="/etc/mkinitcpio.d/$kernel.preset"
[[ -f $preset ]] || {
  echo "Missing ARM mkinitcpio preset: $preset" >&2
  exit 1
}

# The preset and Limine defaults are root-owned shell configuration supplied
# by signed packages or the installer. limine-entry-tool uses a string-indexed
# KERNEL_CMDLINE array, so declare it associative before sourcing the files.
# shellcheck disable=SC1090
source "$preset"
declare -A KERNEL_CMDLINE=()
set +u
for config in \
  /usr/share/limine-entry-tool.d/*.conf \
  /etc/limine-entry-tool.conf \
  /etc/limine-entry-tool.d/*.conf \
  /etc/default/limine; do
  [[ -f $config ]] || continue
  # shellcheck disable=SC1090
  source "$config"
done
set -u

kernel_version="${ALL_kver:-}"
[[ -n $kernel_version ]] || {
  echo "ALL_kver is empty in $preset" >&2
  exit 1
}

esp_path="${ESP_PATH:-/boot}"
kernel_image="$ALL_kver"
[[ -s $kernel_image ]] || {
  echo "Missing ARM kernel image: $kernel_image" >&2
  exit 1
}

cmdline_file="/etc/kernel/cmdline"
[[ -s $cmdline_file ]] || {
  echo "Missing kernel command line: $cmdline_file" >&2
  exit 1
}
cmdline=$(<"$cmdline_file")

uki_prefix="${CUSTOM_UKI_NAME:-omarchy}"
uki_relative="EFI/Linux/${uki_prefix}_${kernel}.efi"
uki_path="$esp_path/$uki_relative"
install -d -m 700 "$(dirname "$uki_path")"
mkinitcpio \
  --kernel "$kernel_version" \
  --uki "$uki_path" \
  --kernelimage "$kernel_image" \
  --cmdline "$cmdline_file"
[[ -s $uki_path ]] || {
  echo "ARM UKI was not created: $uki_path" >&2
  exit 1
}

limine_conf="$esp_path/limine.conf"
[[ -f $limine_conf ]] || {
  echo "Missing Limine configuration: $limine_conf" >&2
  exit 1
}

entry_tmp=$(mktemp)
trap 'rm -f "$entry_tmp"' EXIT
awk '
  /^### BEGIN OMARCHY ARM ENTRY ###$/ { skip=1; next }
  /^### END OMARCHY ARM ENTRY ###$/ { skip=0; next }
  !skip { print }
' "$limine_conf" >"$entry_tmp"

{
  cat "$entry_tmp"
  printf '\n### BEGIN OMARCHY ARM ENTRY ###\n'
  printf '/+Omarchy\n'
  printf 'comment: Omarchy ARM64\n'
  printf '  //%s\n' "$kernel"
  printf '  comment: Kernel version: %s\n' "$kernel_version"
  printf '  protocol: efi\n'
  printf '  path: boot():/%s\n' "$uki_relative"
  printf '  cmdline: %s\n' "$cmdline"
  printf '### END OMARCHY ARM ENTRY ###\n'
} >"$limine_conf"
'''


def _arm_limine_update_script(kernel_package: str) -> str:
    if not re.fullmatch(r"[a-z0-9][a-z0-9@._+-]{1,127}", kernel_package):
        raise RuntimeError(f"Invalid ARM kernel package: {kernel_package!r}")
    return ARM_LIMINE_UPDATE_SCRIPT_TEMPLATE.replace("@KERNEL_PACKAGE@", kernel_package)


def _install_arm_limine_updater(ctx: InstallContext) -> None:
    kernel_package = _storage_intent(ctx).get("kernel", "linux-aarch64")
    updater = ctx.target / "usr" / "local" / "bin" / "omarchy-arm-limine-update"
    updater.parent.mkdir(parents=True, exist_ok=True)
    updater.write_text(_arm_limine_update_script(kernel_package))
    updater.chmod(0o755)

    hook = ctx.target / "etc" / "pacman.d" / "hooks" / "95-omarchy-arm-limine.hook"
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(
        textwrap.dedent(
            f"""\
            [Trigger]
            Operation = Install
            Operation = Upgrade
            Type = Package
            Target = {kernel_package}

            [Action]
            Description = Rebuilding the Omarchy ARM64 boot entry...
            When = PostTransaction
            Exec = /usr/local/bin/omarchy-arm-limine-update
            """
        )
    )


def _strip_shell_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        return value[1:-1]
    return value


def _limine_combined_config_text(ctx: InstallContext, default_text: str) -> str:
    chunks: list[str] = []
    for path in sorted((ctx.target / "usr" / "share" / "limine-entry-tool.d").glob("*.conf")):
        chunks.append(path.read_text())

    legacy_conf = ctx.target / "etc" / "limine-entry-tool.conf"
    if legacy_conf.exists():
        chunks.append(legacy_conf.read_text())

    for path in sorted((ctx.target / "etc" / "limine-entry-tool.d").glob("*.conf")):
        chunks.append(path.read_text())

    # /etc/default/limine has highest priority in limine-entry-tool.
    chunks.append(default_text)
    return "\n".join(chunks)


def _limine_setting(config_text: str, name: str, fallback: str | None = None) -> str | None:
    pattern = re.compile(rf"^\s*{re.escape(name)}\s*=\s*(.*?)\s*$")
    value = fallback
    for line in config_text.splitlines():
        match = pattern.match(line)
        if match:
            value = _strip_shell_quotes(match.group(1))
    return value


def _limine_kernel_cmdline(config_text: str) -> str:
    parts: list[str] = []
    pattern = re.compile(r'^\s*KERNEL_CMDLINE\[default\]\+=\s*(.*?)\s*$')
    for line in config_text.splitlines():
        match = pattern.match(line)
        if match:
            parts.append(_strip_shell_quotes(match.group(1)).strip())
    return " ".join(part for part in parts if part).strip()


def run_chroot_finalizer(ctx: InstallContext) -> None:
    if ctx.defer_provisioning:
        info("› deferred-provisioning install: user finalization deferred to first boot")
        return

    _run_target_setup_command(
        ctx,
        ["/usr/bin/omarchy-provision-user", "--force", "--first-install"],
        user=ctx.username,
    )



# Apple Silicon WiFi/Bluetooth firmware is machine-specific and cannot ship in
# the OS image. The installer leaves it in the EFI system partition, and the
# upstream initramfs hook only exposes it through a symlink that depends on the
# bootloader passing an ESP pointer. When that link breaks the driver silently
# has no firmware and wireless never comes up, so install a real copy into
# /lib/firmware instead of depending on the boot-time reference.
#
# Both radios probe early in boot, before this unit has extracted the
# firmware, so both must be reloaded afterwards. Reloading only brcmfmac left
# the first boot after an install with working Wi-Fi and dead Bluetooth:
# hci_bcm4377 had already failed with "Unable to load firmware" at ~4.5 s.
# The reload is skipped when the initrd already mounted /lib/firmware/vendor
# (omarchy-vendorfw hook): reloading a healthy brcmfmac crashed the BCM4388
# dongle on the M2 Max and left it unable to complete DHCP.
VENDOR_FIRMWARE_UNIT = """\
[Unit]
Description=Install Apple vendor firmware into /lib/firmware
After=local-fs.target
ConditionPathExists=/boot/efi/vendorfw/firmware.tar

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/sh -c 'set -e; src=/boot/efi/vendorfw/firmware.tar; stamp=/var/lib/omarchy/vendor-firmware.stamp; if [ ! -f "$stamp" ] || [ "$src" -nt "$stamp" ]; then install -d -m 0755 /lib/firmware /var/lib/omarchy; tar -xf "$src" -C /lib/firmware; touch -r "$src" "$stamp"; fi'
ExecStartPost=-/usr/bin/sh -c 'mountpoint -q /lib/firmware/vendor && exit 0; for m in brcmfmac hci_bcm4377; do modprobe -r "$m" 2>/dev/null || true; modprobe "$m" 2>/dev/null || true; done'

[Install]
WantedBy=multi-user.target
"""


def install_vendor_firmware(ctx: InstallContext) -> None:
    """Persist the machine's vendor firmware into the installed system."""
    from . import asahi_limine

    if asahi_limine.selected(ctx):
        # The new boot package owns the firmware implementation and ordering.
        asahi_limine.regular(ctx.target / "etc/systemd/system/omarchy-vendor-firmware.service")
        subprocess.run(["arch-chroot", str(ctx.target), "systemctl", "enable",
                        "omarchy-vendor-firmware.service"], check=True)
        return
    info("\u203a installing vendor firmware service")
    unit = ctx.target / "etc" / "systemd" / "system" / "omarchy-vendor-firmware.service"
    unit.parent.mkdir(parents=True, exist_ok=True)
    unit.write_text(VENDOR_FIRMWARE_UNIT)
    subprocess.run(
        ["arch-chroot", str(ctx.target), "systemctl", "enable",
         "omarchy-vendor-firmware.service"],
        check=True,
    )


# The Asahi audio stack keeps the built-in speakers silent unless
# speakersafetyd manages the amplifiers. Arch's preset is "disable *" and no
# install script enables it, so without an explicit enable the installed
# system boots with dead speakers.
def enable_apple_platform_services(ctx: InstallContext) -> None:
    """Enable the Apple Silicon hardware services the desktop depends on."""
    info("\u203a enabling Apple platform services")
    subprocess.run(
        ["arch-chroot", str(ctx.target), "systemctl", "enable",
         "speakersafetyd.service"],
        check=True,
    )

def configure_dns_resolver(ctx: InstallContext) -> None:
    """Put the installed system in systemd-resolved stub mode.

    Arch's systemd-resolved docs explicitly say not to create this symlink from
    inside arch-chroot because /etc/resolv.conf may be a bind mount from the
    live environment. Do it from the ISO against /mnt instead.
    """
    resolv_conf = ctx.target / "etc" / "resolv.conf"
    target = "../run/systemd/resolve/stub-resolv.conf"

    if resolv_conf.is_symlink() and os.readlink(resolv_conf) == target:
        return

    info("› configuring /etc/resolv.conf for systemd-resolved")
    resolv_conf.parent.mkdir(parents=True, exist_ok=True)
    resolv_conf.unlink(missing_ok=True)
    resolv_conf.symlink_to(target)


def configure_arm_package_repository(ctx: InstallContext) -> None:
    """Keep a generic ARM install on its verified ARM package inputs.

    The normal Omarchy finalizer installs the default x86_64 online pacman
    configuration. An ARM ISO carries this marker and replacement explicitly;
    x86_64 media has neither and returns without changing the target.
    """
    media_root = Path(os.environ.get("OMARCHY_ISO_MEDIA_ROOT", "/usr/share/omarchy-iso"))
    repository_record = media_root / "arm-repository"
    runtime_record = media_root / "arm-runtime"
    channel_record = media_root / "arm-runtime-channel"
    pacman_config = media_root / "pacman-online-installed-arm.conf"
    public_key = media_root / "omarchy-arm-repository.asc"

    dependency_record = media_root / "dependency-manifest.json"
    if dependency_record.is_file():
        candidate_record = media_root / "candidate-signing.json"
        dependency_signature = media_root / "dependency-manifest.json.sig"
        candidate_config = media_root / "pacman-online-installed-quattro.conf"
        for required in (candidate_record, dependency_signature, candidate_config):
            if not required.is_file():
                raise RuntimeError(f"Candidate package input is missing: {required}")
        target_state = ctx.target / "var/lib/omarchy/package-snapshots"
        target_state.mkdir(parents=True, exist_ok=True)
        for source, name in ((candidate_record, "QUATTRO-CANDIDATE.json"),
                             (dependency_record, "DEPENDENCIES.json"),
                             (dependency_signature, "DEPENDENCIES.json.sig")):
            shutil.copy(source, target_state / name)
        for name in ("ARM-REPOSITORY", "ARM-RUNTIME"):
            (target_state / name).unlink(missing_ok=True)
        (ctx.target / "var/lib/omarchy/asahi-quattro-release").unlink(missing_ok=True)
        shutil.copy(candidate_config, ctx.target / "etc/pacman.conf")
        sync_dir = ctx.target / "var/lib/pacman/sync"
        if sync_dir.is_dir():
            for stale in sync_dir.iterdir():
                stale.unlink()
        subprocess.run(["pacman", "--sysroot", str(ctx.target), "--disable-sandbox", "--noconfirm", "-Sy"], check=True)
        return

    if not repository_record.exists():
        return
    for required in (runtime_record, channel_record, pacman_config, public_key):
        if not required.is_file():
            raise RuntimeError(f"ARM package input is missing: {required}")

    target_state = ctx.target / "var/lib/omarchy/package-snapshots"
    target_state.mkdir(parents=True, exist_ok=True)
    shutil.copy(repository_record, target_state / "ARM-REPOSITORY")
    candidate_record = media_root / "candidate-signing.json"
    release_state = ctx.target / "var/lib/omarchy/asahi-quattro-release"
    if candidate_record.is_file():
        # The dependency baseline is still recorded above, but this desktop
        # did not come from the older release-tagged runtime bundle.
        shutil.copy(candidate_record, target_state / "QUATTRO-CANDIDATE.json")
        (target_state / "ARM-RUNTIME").unlink(missing_ok=True)
        release_state.unlink(missing_ok=True)
    else:
        shutil.copy(runtime_record, target_state / "ARM-RUNTIME")
        shutil.copy(channel_record, release_state)
        release_state.chmod(0o644)

    target_key = ctx.target / "usr/share/omarchy/omarchy-arm-repository.asc"
    target_key.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(public_key, target_key)
    shutil.copy(pacman_config, ctx.target / "etc/pacman.conf")

    subprocess.run(
        [
            "arch-chroot",
            str(ctx.target),
            "pacman-key",
            "--add",
            "/usr/share/omarchy/omarchy-arm-repository.asc",
        ],
        check=True,
    )
    subprocess.run(
        [
            "arch-chroot",
            str(ctx.target),
            "pacman-key",
            "--lsign-key",
            "C81AC3E2A99556F9B21D5FEA3DD49BC9F8360BDC",
        ],
        check=True,
    )

    # The image was assembled from the build-time offline repository, which
    # leaves its database behind and none for the repositories the installed
    # configuration names. pacstrap leaves an x86_64 install with every
    # configured repository already synced; give the installed system the same
    # so its first `pacman -S` resolves instead of failing with
    # "could not find database". --sysroot reads the target's configuration
    # and keyring without a chroot, so name resolution stays the builder's.
    sync_dir = ctx.target / "var/lib/pacman/sync"
    if sync_dir.is_dir():
        for stale in sync_dir.iterdir():
            stale.unlink()
    subprocess.run(
        [
            "pacman",
            "--sysroot",
            str(ctx.target),
            "--disable-sandbox",
            "--noconfirm",
            "-Sy",
        ],
        check=True,
    )


def configure_login(ctx: InstallContext) -> None:
    sddm_dir = ctx.target / "etc" / "sddm.conf.d"
    sddm_dir.mkdir(parents=True, exist_ok=True)
    (sddm_dir / "99-omarchy-login.conf").write_text(
        "[Theme]\nCurrent=omarchy\n\n"
        "[Users]\nRememberLastUser=true\nRememberLastSession=true\n"
    )

    autologin_conf = sddm_dir / "autologin.conf"
    if ctx.encrypt and not ctx.defer_provisioning:
        autologin_conf.write_text(
            "[Autologin]\n"
            f"User={ctx.username}\n"
            "Session=omarchy.desktop\n"
        )
    else:
        # deferred-provisioning installs have no user yet; omarchy-provision-owner writes autologin
        # and SDDM state at first boot once the owner exists.
        autologin_conf.unlink(missing_ok=True)

    if not ctx.defer_provisioning:
        state_dir = ctx.target / "var" / "lib" / "sddm"
        state_dir.mkdir(parents=True, exist_ok=True)
        (state_dir / "state.conf").write_text(
            f"[Last]\nSession=omarchy.desktop\nUser={ctx.username}\n"
        )
        subprocess.run(
            ["arch-chroot", str(ctx.target), "chown", "sddm:sddm",
             "/var/lib/sddm", "/var/lib/sddm/state.conf"],
            check=False, capture_output=True,
        )

    autologin = ctx.target / "etc" / "systemd" / "system" / "getty@tty1.service.d" / "autologin.conf"
    autologin.unlink(missing_ok=True)

    subprocess.run(
        ["arch-chroot", str(ctx.target), "systemctl", "enable", "sddm.service"],
        check=False, capture_output=True,
    )


def configure_ssh_access(ctx: InstallContext) -> None:
    if ctx.authorized_keys_path is None:
        return

    keys = _authorized_keys(ctx.authorized_keys_path)

    if ctx.defer_provisioning:
        # No user to authorize yet. Stage the keys in provisioning state for
        # omarchy-provision-owner to install once first boot creates the owner, and
        # still open the door (sshd + ufw) below.
        info(f"› staging {len(keys)} SSH key(s) for the first-boot user")
        provisioning_dir = ctx.target / PROVISION_STATE_DIR
        provisioning_dir.mkdir(parents=True, exist_ok=True)
        staged = provisioning_dir / "authorized_keys"
        staged.write_text("".join(f"{key}\n" for key in keys))
        staged.chmod(0o600)
    else:
        info(f"› installing {len(keys)} SSH key(s) for {ctx.username}")

        ssh_dir = ctx.target / "home" / ctx.username / ".ssh"
        ssh_dir.mkdir(parents=True, exist_ok=True)
        ssh_dir.chmod(0o700)

        authorized_keys = ssh_dir / "authorized_keys"
        authorized_keys.write_text("".join(f"{key}\n" for key in keys))
        authorized_keys.chmod(0o600)

        # Ask the target for the uid rather than assuming the first user is 1000.
        # Uncaptured so a failure shows up in the install log, and checked because
        # a root-owned authorized_keys is one sshd refuses to read.
        subprocess.run(
            ["arch-chroot", str(ctx.target), "chown", "-R",
             f"{ctx.username}:{ctx.username}", f"/home/{ctx.username}/.ssh"],
            check=True,
        )

    info("› enabling sshd")
    subprocess.run(
        ["arch-chroot", str(ctx.target), "systemctl", "enable", "sshd.service"],
        check=True,
    )

    # Open port 22 in the target's ufw, which runs default-deny incoming, so an
    # enabled sshd is still unreachable -- connections time out rather than
    # being refused.
    #
    # ufw cannot reach netfilter from inside the chroot and exits non-zero
    # saying so, but it writes the rule to user.rules first, and that file is
    # what ufw.service loads on first boot. So the exit status is the wrong
    # thing to check here; the rule landing in the file is the thing that
    # matters.
    info("› allowing SSH through ufw")
    subprocess.run(["arch-chroot", str(ctx.target), "ufw", "allow", "ssh"], check=False)

    rules = ctx.target / "etc" / "ufw" / "user.rules"
    text = rules.read_text() if rules.exists() else ""
    if "--dport 22 -j ACCEPT" not in text:
        raise RuntimeError(f"ufw did not record an allow rule for port 22 in {rules}")


def _authorized_keys(path: Path) -> list[str]:
    """Read the autoinstall authorized_keys: sshd's own format, one public key
    per line, with blank lines and # comments dropped.

    Raise rather than skip on anything unusable. An install that "succeeds"
    into a machine nobody can log into is worse than one that stops with the
    reason on screen.
    """
    try:
        lines = path.read_text().splitlines()
    except OSError as exc:
        raise RuntimeError(f"{path} is not readable: {exc}") from exc

    keys = [line.strip() for line in lines]
    keys = [key for key in keys if key and not key.startswith("#")]
    if not keys:
        raise RuntimeError(f"{path} contains no SSH keys")

    return keys


TAILSCALE_AUTHKEY_TARGET = "/etc/tailscale/authkey"


TAILSCALE_JOIN_UNIT = f"""\
[Unit]
Description=Join the tailnet with the auth key staged by autoinstall
Wants=network-online.target
After=network-online.target tailscaled.service
Requires=tailscaled.service
ConditionPathExists={TAILSCALE_AUTHKEY_TARGET}

[Service]
Type=simple
ExecStart=/usr/bin/sh -c 'until tailscale up --auth-key file:{TAILSCALE_AUTHKEY_TARGET}; do sleep 15; done; rm -f {TAILSCALE_AUTHKEY_TARGET}; systemctl disable omarchy-tailscale-join.service'

[Install]
WantedBy=multi-user.target
"""


def configure_tailscale(ctx: InstallContext) -> None:
    if ctx.tailscale_authkey_path is None:
        return

    key = _tailscale_authkey(ctx.tailscale_authkey_path)

    # An ISO built before tailscale was bundled installs nothing, and a staged
    # key with no binary would fail silently forever on first boot.
    if not (ctx.target / "usr" / "bin" / "tailscale").exists():
        raise RuntimeError("tailscale is not installed on the target; this ISO does not bundle it")

    info("› staging Tailscale auth key")
    ts_dir = ctx.target / "etc" / "tailscale"
    ts_dir.mkdir(parents=True, exist_ok=True)
    ts_dir.chmod(0o700)
    authkey = ts_dir / "authkey"
    authkey.write_text(f"{key}\n")
    authkey.chmod(0o600)

    info("› enabling tailscaled and the first-boot join")
    unit = ctx.target / "etc" / "systemd" / "system" / "omarchy-tailscale-join.service"
    unit.parent.mkdir(parents=True, exist_ok=True)
    unit.write_text(TAILSCALE_JOIN_UNIT)
    subprocess.run(
        ["arch-chroot", str(ctx.target), "systemctl", "enable",
         "tailscaled.service", "omarchy-tailscale-join.service"],
        check=True,
    )

    # Same dance as configure_ssh_access: ufw cannot reach netfilter from the
    # chroot and exits non-zero, but it records the rule in user.rules first,
    # and that file is what ufw.service loads on first boot. Without the rule
    # the node joins the tailnet and is then unreachable over it.
    info("› allowing tailnet traffic through ufw")
    subprocess.run(
        ["arch-chroot", str(ctx.target), "ufw", "allow", "in", "on", "tailscale0"],
        check=False,
    )

    rules = ctx.target / "etc" / "ufw" / "user.rules"
    text = rules.read_text() if rules.exists() else ""
    if "-i tailscale0 -j ACCEPT" not in text:
        raise RuntimeError(f"ufw did not record an allow rule for tailscale0 in {rules}")


def _tailscale_authkey(path: Path) -> str:
    """Read the autoinstall tailscale_authkey: exactly one key, with blank
    lines and # comments dropped. No format validation beyond that -- key
    formats are Tailscale's to change.

    Raise rather than skip on anything unusable, same reasoning as
    _authorized_keys: a machine that "succeeds" into never joining the
    tailnet is worse than one that stops with the reason on screen.
    """
    try:
        lines = path.read_text().splitlines()
    except OSError as exc:
        raise RuntimeError(f"{path} is not readable: {exc}") from exc

    keys = [line.strip() for line in lines]
    keys = [key for key in keys if key and not key.startswith("#")]
    if not keys:
        raise RuntimeError(f"{path} contains no auth key")
    if len(keys) > 1:
        raise RuntimeError(f"{path} contains {len(keys)} keys; expected exactly one")

    return keys[0]


def validate_boot(ctx: InstallContext) -> None:
    _assert_boot_hooks_restored(ctx)

    from . import asahi_limine

    if asahi_limine.selected(ctx):
        asahi_limine.validate(ctx)
        if ctx.is_protected:
            _validate_pre_mounted_filesystems(ctx)
        _validate_provisioning_state(ctx)
        return

    if _boot_backend(ctx) == "asahi-grub":
        _validate_asahi_grub_boot(ctx)
        if ctx.is_protected:
            _validate_pre_mounted_filesystems(ctx)
        if ctx.defer_provisioning:
            _validate_provisioning_state(ctx)
        return

    boot = _boot_intent(ctx)
    storage = _storage_intent(ctx)
    esp_mount = ctx.target / boot["esp_mount"].lstrip("/")

    limine_conf = esp_mount / "limine.conf"
    if not limine_conf.exists():
        raise RuntimeError(f"{limine_conf} missing")
    limine_conf_text = limine_conf.read_text()
    if "Omarchy" not in limine_conf_text:
        raise RuntimeError(f"{limine_conf} has no Omarchy entry")

    encryption_parameter = "rd.luks.name=" if _is_arm_machine() else "cryptdevice="
    if ctx.encrypt and encryption_parameter not in limine_conf_text:
        raise RuntimeError(
            f"Encrypted install but {limine_conf} has no {encryption_parameter}"
        )
    if ctx.encrypt and _is_arm_machine():
        encryption_hooks = (
            ctx.target
            / "etc"
            / "mkinitcpio.conf.d"
            / "90-omarchy-arm-encryption.conf"
        )
        if not encryption_hooks.exists() or "sd-encrypt" not in encryption_hooks.read_text():
            raise RuntimeError(f"Encrypted ARM install but {encryption_hooks} is missing")
        if "console=tty0" not in limine_conf_text:
            raise RuntimeError(f"Encrypted ARM install but {limine_conf} has no graphical console")
        if "plymouth.ignore-serial-consoles" not in limine_conf_text:
            raise RuntimeError(
                f"Encrypted ARM install but {limine_conf} may suppress Plymouth for serial"
            )

    kernel_cmdline = ctx.target / "etc" / "kernel" / "cmdline"
    if not kernel_cmdline.exists():
        raise RuntimeError(f"{kernel_cmdline} missing — UKI would have no cmdline")

    default_limine = ctx.target / "etc" / "default" / "limine"
    config_text = _limine_combined_config_text(ctx, default_limine.read_text())
    uki_prefix = _limine_setting(config_text, "CUSTOM_UKI_NAME", "omarchy") or "omarchy"
    kernel = storage.get("kernel") or (ctx.user_configuration.get("kernels") or ["linux"])[0]

    if arch.has_uefi():
        limine_binary = esp_mount / boot.get("esp_path", "/EFI/limine").lstrip("/") / boot.get("efi_binary", _limine_efi_names()[1])
        if not limine_binary.exists() or limine_binary.stat().st_size == 0:
            raise RuntimeError(f"{limine_binary} missing or empty")

        # Hardware packages (omarchy-hw-intel-ptl, …) can swap the kernel out
        # from under us mid-install, so trust what's on disk over what we asked
        # for and only fall back to the configured name when nothing's there.
        uki_dir = esp_mount / "EFI" / "Linux"
        candidates = _installed_kernels(ctx) or [kernel]
        ukis = [uki_dir / f"{uki_prefix}_{name}.efi" for name in candidates]
        if not any(uki.exists() and uki.stat().st_size for uki in ukis):
            raise RuntimeError(f"{' / '.join(str(uki) for uki in ukis)} missing or empty")

        post = _read_efibootmgr()
        if not _find_label_entries(post["entries"], "Limine"):
            raise RuntimeError("no 'Limine' entry registered in efibootmgr")

    if ctx.is_protected:
        _validate_pre_mounted_filesystems(ctx)

    if ctx.defer_provisioning:
        _validate_provisioning_state(ctx)


def _validate_asahi_grub_boot(ctx: InstallContext) -> None:
    boot = _boot_intent(ctx)
    storage = _storage_intent(ctx)
    esp = ctx.target / boot["esp_mount"].lstrip("/")
    boot_dir = ctx.target / storage.get("boot_mount", "/boot").lstrip("/")
    kernel = storage.get("kernel") or "linux-asahi"

    populated = (
        esp / "m1n1/boot.bin",
        esp / "EFI/BOOT/BOOTAA64.EFI",
        boot_dir / f"vmlinuz-{kernel}",
        boot_dir / f"initramfs-{kernel}.img",
        boot_dir / "grub/grub.cfg",
    )
    for path in populated:
        if not path.is_file() or not path.stat().st_size:
            raise RuntimeError(f"Asahi boot artifact missing or empty: {path}")

    grub_config = (boot_dir / "grub/grub.cfg").read_text(errors="ignore")
    for expected in ("Omarchy", f"vmlinuz-{kernel}", f"initramfs-{kernel}.img"):
        if expected not in grub_config:
            raise RuntimeError(f"Asahi GRUB config has no {expected}: {boot_dir / 'grub/grub.cfg'}")

    hooks = ctx.target / "etc/mkinitcpio.conf.d/90-omarchy-asahi.conf"
    if not hooks.is_file() or "asahi" not in hooks.read_text():
        raise RuntimeError(f"Asahi initramfs hook configuration missing: {hooks}")


def _validate_provisioning_state(ctx: InstallContext) -> None:
    """An deferred-provisioning install that boots without a working first-boot setup is a
    user-less brick; insist the armed state is complete before reboot."""
    provisioning_dir = ctx.target / PROVISION_STATE_DIR
    if not (provisioning_dir / "pending").exists():
        raise RuntimeError(f"deferred-provisioning install but {provisioning_dir / 'pending'} is missing")

    link = ctx.target / "etc/systemd/system/multi-user.target.wants/omarchy-provision-owner.service"
    if not link.is_symlink():
        raise RuntimeError("deferred-provisioning install but omarchy-provision-owner.service is not enabled")

    if not list((provisioning_dir / "packages").glob("node-v*.tar.gz")):
        raise RuntimeError(f"deferred-provisioning install but no Node tarball staged in {provisioning_dir / 'packages'}")

    if _provision_install_encrypted(ctx):
        for required in (provisioning_dir / "luks-key", ctx.target / PROVISION_KEYFILE):
            if not required.exists():
                raise RuntimeError(f"encrypted deferred-provisioning install but {required} is missing")
        limine_conf_text = (
            ctx.target / _boot_intent(ctx)["esp_mount"].lstrip("/") / "limine.conf"
        ).read_text()
        key_parameter = "rd.luks.key=" if _is_arm_machine() else "cryptkey=rootfs:"
        if key_parameter not in limine_conf_text:
            raise RuntimeError(
                "encrypted deferred-provisioning install but limine.conf has no "
                f"{key_parameter} for auto-unlock"
            )


def _assert_boot_hooks_restored(ctx: InstallContext) -> None:
    """Never hand over a system whose boot-image rebuild hooks are unusable.

    run_system_finalizer defers 90-mkinitcpio-install.hook inside the target and
    restores it in a finally, but a mask that survived would be invisible until
    the first kernel update shipped an unbootable system. Repair, then insist on
    the backend's actual maintenance path: Limine's /etc override or Arch and
    Asahi's vendor hooks for the GRUB image.
    """
    cleanup_target_hook_masks(ctx)

    hooks_dir = ctx.target / "etc/pacman.d/hooks"
    for name in TARGET_DEFERRED_BOOT_HOOKS:
        path = hooks_dir / name
        if _is_devnull_symlink(path):
            raise RuntimeError(f"{path} is still masked to /dev/null")
        backup = hooks_dir / f"{name}.omarchy-backup"
        if backup.exists() or backup.is_symlink():
            raise RuntimeError(f"{backup} left behind by the install-time hook mask")

    if _boot_backend(ctx) == "asahi-grub":
        _assert_asahi_boot_update_hooks(ctx)
        return

    for name in TARGET_DEFERRED_BOOT_HOOKS:
        path = hooks_dir / name
        # limine-mkinitcpio-hook is a hard dependency of the Omarchy runtime
        # package, so the real hook is on disk before the mask ever goes up and
        # must be on disk again now.
        if not path.is_file():
            raise RuntimeError(f"{path} is missing — future kernel updates would ship no UKI")


def _assert_asahi_boot_update_hooks(ctx: InstallContext) -> None:
    kernel = _storage_intent(ctx).get("kernel") or "linux-asahi"
    required_text = {
        ctx.target / "usr/share/libalpm/hooks/90-mkinitcpio-install.hook": (
            "Target = usr/lib/modules/*/vmlinuz",
            "Exec = /usr/share/libalpm/scripts/mkinitcpio install",
        ),
        ctx.target / "usr/share/libalpm/hooks/95-m1n1-install.hook": (
            "Target = usr/lib/asahi-boot/*",
            "Exec = /usr/bin/update-m1n1",
        ),
        ctx.target / f"etc/mkinitcpio.d/{kernel}.preset": (
            f"/boot/vmlinuz-{kernel}",
            f"/boot/initramfs-{kernel}.img",
        ),
    }
    for path, tokens in required_text.items():
        if not path.is_file():
            raise RuntimeError(f"Asahi boot update contract is missing {path}")
        text = path.read_text(errors="ignore")
        for token in tokens:
            if token not in text:
                raise RuntimeError(f"Asahi boot update contract in {path} has no {token}")

    for path in (
        ctx.target / "usr/share/libalpm/scripts/mkinitcpio",
        ctx.target / "usr/bin/update-m1n1",
    ):
        if not path.is_file() or not os.access(path, os.X_OK):
            raise RuntimeError(f"Asahi boot update helper is missing or not executable: {path}")


def _installed_kernels(ctx: InstallContext) -> list[str]:
    names = []
    for pkgbase in sorted((ctx.target / "usr" / "lib" / "modules").glob("*/pkgbase")):
        name = pkgbase.read_text().strip()
        if name and name not in names:
            names.append(name)
    return names


def _validate_pre_mounted_filesystems(ctx: InstallContext) -> None:
    storage = _storage_intent(ctx)
    fstab = ctx.target / "etc" / "fstab"
    if not fstab.exists():
        raise RuntimeError(f"{fstab} missing")
    fstab_text = fstab.read_text()
    btrfs_uuid = _blkid_uuid(_btrfs_root_device(ctx))
    esp_uuid = _blkid_uuid(_esp_device(ctx))
    if btrfs_uuid not in fstab_text:
        raise RuntimeError(f"{fstab} missing btrfs UUID {btrfs_uuid}")
    if esp_uuid not in fstab_text:
        raise RuntimeError(f"{fstab} missing ESP UUID {esp_uuid}")

    if storage.get("luks_uuid"):
        crypttab = ctx.target / "etc" / "crypttab.initramfs"
        if not crypttab.exists():
            raise RuntimeError(f"{crypttab} missing")
        if storage["luks_uuid"] not in crypttab.read_text():
            raise RuntimeError(f"{crypttab} missing LUKS UUID {storage['luks_uuid']}")


def create_factory_snapshot(ctx: InstallContext) -> None:
    from . import asahi_limine

    limine_image = asahi_limine.selected(ctx)
    fstype = _findmnt_value(ctx.target, "FSTYPE")
    if fstype != "btrfs":
        if limine_image:
            raise RuntimeError("Apple Limine image requires a btrfs factory snapshot")
        info(f"› target root is {fstype or 'unknown'}, not btrfs; skipping factory snapshot")
        return

    options = (_findmnt_value(ctx.target, "OPTIONS") or "").split(",")
    if not any(opt in ("subvol=/@", "subvol=@") for opt in options):
        if limine_image:
            raise RuntimeError("Apple Limine factory source must be @")
        info("› target root is not the @ subvolume; skipping factory snapshot")
        return

    device = require_text(
        (_findmnt_value(ctx.target, "SOURCE") or "").split("[")[0],
        f"the btrfs device backing {ctx.target}",
    )
    if not device:
        raise RuntimeError(f"could not determine the btrfs device backing {ctx.target}")

    top = ctx.state_dir / "factory-top"
    top.mkdir(parents=True, exist_ok=True)
    subprocess.run(["mount", "-o", "subvolid=5", device, str(top)], check=True)
    try:
        root_subvol = top / "@"
        if not root_subvol.is_dir():
            raise RuntimeError(f"no @ subvolume at the top level of {device}")

        factory = top / "@factory"
        if factory.exists():
            subprocess.run(
                ["btrfs", "subvolume", "delete", str(factory)],
                check=True, capture_output=True,
            )

        if limine_image:
            # Scrub before snapshotting: root and sealed factory cannot share
            # the disposable builder's identity or package-signing secrets.
            asahi_limine.scrub_identity(ctx.target)
        info("› snapshotting @ as @factory (read-only)")
        subprocess.run(
            ["btrfs", "subvolume", "snapshot", str(root_subvol), str(factory)],
            check=True,
        )
        _scrub_factory_snapshot(factory)
        if limine_image:
            asahi_limine.scrub_factory(factory)
        subprocess.run(
            ["btrfs", "property", "set", "-ts", str(factory), "ro", "true"],
            check=True,
        )
    finally:
        subprocess.run(["umount", str(top)], check=False, capture_output=True)


FACTORY_SCRUB_PATHS = (
    "var/lib/omarchy/provisioning/authorized_keys",
    "var/lib/omarchy/provisioning/luks-key",
    "etc/omarchy/provisioning.key",
    "etc/limine-entry-tool.d/99-omarchy-provisioning-unlock.conf",
    "etc/mkinitcpio.conf.d/99-omarchy-provisioning-key.conf",
    "etc/tailscale/authkey",
    "etc/systemd/system/omarchy-tailscale-join.service",
    "etc/systemd/system/multi-user.target.wants/omarchy-tailscale-join.service",
)


def _scrub_factory_snapshot(factory: Path) -> None:
    for rel in FACTORY_SCRUB_PATHS:
        (factory / rel).unlink(missing_ok=True)


def _findmnt_value(path: Path, column: str) -> str | None:
    res = capture(["findmnt", "-no", column, str(path)])
    value = res.stdout.strip()
    return value if res.returncode == 0 and value else None
